import React from 'react'
import { AiOutlineUser } from "react-icons/ai";
import { FaUsers } from 'react-icons/fa6';
import { GoPlus } from 'react-icons/go';
import { IoLogOut } from 'react-icons/io5';
import { MdOutlineDashboard } from 'react-icons/md';
import { SiMicrosoftacademic } from 'react-icons/si';
export const icons =
   { login:<AiOutlineUser/>,
     users:<FaUsers/>,
     academic_sessions:<SiMicrosoftacademic />,
     create_academic_session:<GoPlus />,
     dashboard:<MdOutlineDashboard/>,
     create_user:<GoPlus/>,
     campuses:<SiMicrosoftacademic />,
     create_campus:<GoPlus />,
  create_admission: <GoPlus />,
  create_promotion: <GoPlus />,
  student_id_card: <AiOutlineUser />,
  create_student_id_card: <GoPlus />,
  fees: <SiMicrosoftacademic />,
  create_fee: <GoPlus />,
  fee_receipts: <SiMicrosoftacademic />,
  create_fee_receipt: <GoPlus />,
  fee_heads: <SiMicrosoftacademic />,
  create_fee_head: <GoPlus />,
  income_groups: <SiMicrosoftacademic />,
  create_income_group: <GoPlus />,
  fee_templates: <SiMicrosoftacademic />,
  create_fee_template: <GoPlus />,
  expense_heads: <SiMicrosoftacademic />,
  create_expense_head: <GoPlus />,
  expense_groups: <SiMicrosoftacademic />,
  create_expense_group: <GoPlus />,
  expenses: <SiMicrosoftacademic />,
  create_expense: <GoPlus />,
  education_boards: <SiMicrosoftacademic />,
  create_education_board: <GoPlus />,
  school_types: <SiMicrosoftacademic />,
  create_school_type: <GoPlus />,
  schools: <SiMicrosoftacademic />,
  create_school: <GoPlus />,
  departments: <SiMicrosoftacademic />,
  create_department: <GoPlus />,
  designations: <SiMicrosoftacademic />,
  create_designation: <GoPlus />,
  academic_standards: <SiMicrosoftacademic />,
  create_academic_standard: <GoPlus />,
  academic_classes: <SiMicrosoftacademic />,
  create_academic_class: <GoPlus />,
  sections: <SiMicrosoftacademic />,
  create_section: <GoPlus />,
  subject_groups: <SiMicrosoftacademic />,
  create_subject_group: <GoPlus />,
  subjects: <SiMicrosoftacademic />,
  create_subject: <GoPlus />,
  buildings: <SiMicrosoftacademic />,
  create_building: <GoPlus />,
  floors: <SiMicrosoftacademic />,
  create_floor: <GoPlus />,
  rooms: <SiMicrosoftacademic />,
  create_room: <GoPlus />,
  documents: <SiMicrosoftacademic />,
  examinations: <SiMicrosoftacademic />,
  create_examination: <GoPlus />,
  examination_types: <SiMicrosoftacademic />,
  create_examination_type: <GoPlus />,
  examination_standard: <SiMicrosoftacademic />,
  create_examination_standard: <GoPlus />,
  examination_schedule: <SiMicrosoftacademic />,
  create_examination_schedule: <GoPlus />,
  examination_result: <SiMicrosoftacademic />,
  create_examination_result: <GoPlus />,
  daily_collection_report: <SiMicrosoftacademic />,
  monthly_collection_report: <SiMicrosoftacademic />,
  exam_fees_collection_report: <SiMicrosoftacademic />,
     logout:<IoLogOut />,

    }


